{% set name = "bordado" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bordado-{{ version }}.tar.gz
  sha256: 25e9f5110f5e8b396138be3b285b0ddaa940a27f6007e54c5e1f89df152c97e8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61
    - wheel
    - setuptools-scm >=8.0.3
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.23
    - scipy >=1.8

test:
  imports:
    - bordado
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Create, manipulate, and split geographic coordinates
  home: https://www.fatiando.org/bordado/
  dev_url: https://github.com/fatiando/bordado
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - leouieda
